set_power_profile:
  name: Set Power Profile
  description: Set the power profile for the miner (profiles are loaded dynamically from miner)
  target:
    entity:
      domain: switch
  fields:
    profile:
      name: Profile
      description: Power profile to set (e.g., "default", "310MHz", "435MHz", "560MHz", "685MHz", "810MHz")
      example: "default"
      required: true
      selector:
        text:

set_power_limit:
  name: Set Power Limit
  description: Set the power limit for the miner in watts
  target:
    entity:
      domain: switch
  fields:
    power_limit:
      name: Power Limit
      description: Power limit in watts
      example: 3000
      required: true
      selector:
        number:
          min: 500
          max: 50000
          unit_of_measurement: "W"

emergency_stop:
  name: Emergency Stop
  description: Emergency stop all mining operations
  target:
    entity:
      domain: switch

solar_max:
  name: Solar Max
  description: Set to solar max mode (4200W)
  target:
    entity:
      domain: switch

eco_mode:
  name: Eco Mode
  description: Set to eco mode (1500W)
  target:
    entity:
      domain: switch

set_pool:
  name: Set Mining Pool
  description: Add and switch to a new mining pool
  target:
    entity:
      domain: switch
  fields:
    pool_url:
      name: Pool URL
      description: Mining pool URL
      example: "stratum+tcp://pool.example.com:4444"
      required: true
      selector:
        text:
    pool_user:
      name: Pool User
      description: Mining pool username
      example: "your_username"
      required: true
      selector:
        text:
    pool_password:
      name: Pool Password
      description: Mining pool password
      example: "x"
      default: "x"
      selector:
        text:
    priority:
      name: Priority
      description: Pool priority (0 = highest)
      example: 0
      default: 0
      selector:
        number:
          min: 0
          max: 10

sleep_miner:
  name: Sleep Miner
  description: Put the miner into sleep mode (curtail sleep) - reduces power consumption to minimum while keeping the miner responsive
  target:
    entity:
      domain: switch

wake_miner:
  name: Wake Miner
  description: Wake up the miner from sleep mode (curtail wakeup) - restores normal mining operations
  target:
    entity:
      domain: switch